/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package formulario;

import archivo.Archivo;
import entidad.Sensor;
import entidad.Actuador;
import general.ValidadorSen;
import general.ValidadorA;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author vr
 */
public class FrmEdicionSensor extends javax.swing.JFrame {
    FrmMantenimientoSensor frm;
    /**
     * Creates new form FrmIngresoPersona
     */
    public FrmEdicionSensor(String id, FrmMantenimientoSensor frm) {
        initComponents();
        this.frm = frm;
        try{
            ArrayList<Sensor> registros = Archivo.obtener_registros();
            for(Sensor p:registros){
                if(p.getId().equals(id)){
                    tfId.setText(id);
                    tfNombre.setText(p.getNombre());
                    tfApellidos.setText(p.getApellidos());
                    tfEdad.setText(String.valueOf(p.getEdad()));
                }
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,
            "Ocurrió un error al consultar los datos del registro",
            "Edición",
            JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lCedula = new javax.swing.JLabel();
        lNombres = new javax.swing.JLabel();
        lApellidos = new javax.swing.JLabel();
        lEdad = new javax.swing.JLabel();
        tfCedula = new javax.swing.JTextField();
        tfNombres = new javax.swing.JTextField();
        tfApellidos = new javax.swing.JTextField();
        tfEdad = new javax.swing.JTextField();
        bEditar = new javax.swing.JButton();
        bLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lCedula.setText("CÉDULA:");

        lNombres.setText("NOMBRES:");

        lApellidos.setText("APELLIDOS:");

        lEdad.setText("EDAD:");

        tfCedula.setEditable(false);

        bEditar.setText("Editar");
        bEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarActionPerformed(evt);
            }
        });

        bLimpiar.setText("Limpiar");
        bLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lCedula)
                            .addComponent(lNombres)
                            .addComponent(lApellidos)
                            .addComponent(lEdad))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfCedula)
                            .addComponent(tfNombres)
                            .addComponent(tfApellidos)
                            .addComponent(tfEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(bEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bLimpiar)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lCedula)
                    .addComponent(tfCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lNombres)
                    .addComponent(tfNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lApellidos)
                    .addComponent(tfApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lEdad)
                    .addComponent(tfEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEditar)
                    .addComponent(bLimpiar))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean formularioValido(){
        if(tfCedula.getText().equals("") ||
           tfNombres.getText().equals("") ||
           tfApellidos.getText().equals("") ||
           tfEdad.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Formulario incompleto","Validación",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        try{
            Integer.parseInt(tfEdad.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "La edad debe ser un número","Validación",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    
    private void bEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarActionPerformed
        // TODO add your handling code here:
        if(formularioValido()){
            String cedula       = tfCedula.getText();
            String nombres      = tfNombres.getText();
            String apellidos    = tfApellidos.getText();
            int edad            = Integer.parseInt(tfEdad.getText());
            Sensor p = new Sensor(cedula, nombres, apellidos, edad);
            if(Archivo.editar_registro(p)){
                JOptionPane.showMessageDialog(this,"Se editó correctamente la persona", "Edición",JOptionPane.INFORMATION_MESSAGE);            
                this.frm.consultarRegistros();
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this,"Ocurrió un error en la edición", "Error",JOptionPane.ERROR_MESSAGE);            
            }
        }
    }//GEN-LAST:event_bEditarActionPerformed

    private void bLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarActionPerformed
        // TODO add your handling code here:
        limpiarFormulario();
    }//GEN-LAST:event_bLimpiarActionPerformed

    private void limpiarFormulario(){
        tfNombres.setText("");
        tfApellidos.setText("");
        tfEdad.setText("");    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bLimpiar;
    private javax.swing.JLabel lApellidos;
    private javax.swing.JLabel lCedula;
    private javax.swing.JLabel lEdad;
    private javax.swing.JLabel lNombres;
    private javax.swing.JTextField tfApellidos;
    private javax.swing.JTextField tfCedula;
    private javax.swing.JTextField tfEdad;
    private javax.swing.JTextField tfNombres;
    // End of variables declaration//GEN-END:variables
}
